### ISSUE TITLE
TypeError: superclass mismatch for class GoogleTagManager

### ISSUE THREAD

**Issue by dseeker** [t-richards/jekyll-google-tag-manager#8] opened 2019-10-15 12:49 UTC
```
bundler: failed to load command: jekyll (/srv/vendor/bundle/ruby/2.6.0/bin/jekyll)
TypeError: superclass mismatch for class GoogleTagManager
  /srv/vendor/bundle/ruby/2.6.0/gems/jekyll-google-tag-manager-1.0.2/lib/jekyll-google-tag-manager/version.rb:6:in `<module:Jekyll>'
  /srv/vendor/bundle/ruby/2.6.0/gems/jekyll-google-tag-manager-1.0.2/lib/jekyll-google-tag-manager/version.rb:5:in `<top (required)>'
  /srv/vendor/bundle/ruby/2.6.0/gems/jekyll-google-tag-manager-1.0.2/lib/jekyll-google-tag-manager.rb:4:in `require'
  /srv/vendor/bundle/ruby/2.6.0/gems/jekyll-google-tag-manager-1.0.2/lib/jekyll-google-tag-manager.rb:4:in `<top (required)>'
  /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `require'
  /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
  /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
  /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
  /usr/local/bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
  /usr/local/bundle/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
  /srv/vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.6/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
  /srv/vendor/bundle/ruby/2.6.0/gems/jekyll-3.8.6/exe/jekyll:11:in `<top (required)>'
  /srv/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `load'
  /srv/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `<top (required)>'
```

**Comment by t-richards** [comment] 2019-10-15 15:32
Duplicate of #7 (which needs a better title).

**Closed as completed by t-richards** 2019-10-15 15:32 UTC
